export * from './domain/schema'
export * from './domain/compile'
export * from './domain/aggregate'
// metrics/answers: наружу — только публичное API. round1/round2 и coerceExclusive
// остаются внутренними (импортируются из своих модулей напрямую, в т.ч. тестами).
export { nps, csat, ces, distribution } from './domain/metrics'
export type { NpsSummary, CsatSummary, CesSummary } from './domain/metrics'
export { validateAnswer, normalizeAnswer, buildResponseAnswers } from './domain/answers'
export type { BuiltAnswers } from './domain/answers'
export { MemoryStore } from './store/memory'
export { PgStore, queryableFromPool } from './store/pg'
export type { PoolLike } from './store/pg'
// HTTP-слой (framework-agnostic): хендлеры + анти-абьюз. Node-адаптер НЕ в barrel
// (не тянем node:http в ядро) — импортируйте напрямую: import { startServer } from '.../server/node'
export { createApi, SUPPORTED_SCHEMA_VERSION } from './api/handlers'
export type { Api, ApiDeps, ApiResult, SessionInput, SubmitInput } from './api/handlers'
export { MemoryNonceStore } from './api/nonce'
export type { NonceStore } from './api/nonce'
export { SlidingWindowLimiter } from './api/ratelimit'
export type { RateLimiter } from './api/ratelimit'
// Bitrix24 (#3): шифрование OAuth-токенов + refresh-flow (fetch/pg.Pool даёт слой деплоя)
export { TokenCipher, loadTokenKey } from './bitrix24/crypto'
export type { EncryptedBlob } from './bitrix24/crypto'
export { Bitrix24OAuth, OAuthError } from './bitrix24/oauth'
export type { OAuthTokens, HttpFetch, HttpResponse, Bitrix24OAuthOptions } from './bitrix24/oauth'
export { PortalTokenStore } from './bitrix24/portal'
export { DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE } from './store/types'
export type { IStore, ResponsePage, ResponsePageOptions } from './store/types'
export type { Queryable, PgStoreOptions, AggregateFilter } from './store/pg'
